package exceptionlab;

public class Exceptiontest {
	public static void main(String[] args)throws Exception {
	
		Exceptiontest et=new Exceptiontest();
		et.jungalBook();
	
	//System.out.println(arr[0]);
}
	
	public void jungalBook() throws Exception
	{
		int arr[]={1,2};
		try{
		System.out.println(arr[2]);
	      }
		
		catch(Exception e)
		{
			
			
		}
	finally{
			
			System.out.println("Inside finally block");
			throw new ArrayIndexOutOfBoundsException(" basi boudhi");
		}
		
	}
	
}
